# This is a basic workflow to help you get started with Actions

name: Release to Heroku

on:
  # Only when new version tags are pushed
  push:
    branches:
      - "!*"
    tags:
      - "v*"

  # Or manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Publish and release to Heroku
        shell: pwsh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          .\eng\release.ps1
